### PR TITLE
Support libgbinder for Android 11

### PR DESCRIPTION
**Pull request by adglkh**
This PR honors a bunch of protocol changes to 
 . RPC 
 . a few commands of service manager (E.g. list, add)
and support libgbinder for Android 11

### CODE REVIEW

**Comment by leowang1225** [comment]
this seem works to me, but debian test failed

**Comment by monich** [comment]
Interesting... That will take a bit of time to review, please be patient!

**Comment by monich** [comment]
I've cherry-picked `gbinder_local_reply_append_fd()` commit to master as it's totally unrelated (should've been submitted as a separate PR), @mlehtima is looking at the rest of the stuff. Stay tuned.

**Comment by mlehtima** [comment]
These changes have been integrated in https://github.com/mer-hybris/libgbinder/pull/79. Closing this.

**Comment by adglkh** [comment]
Thanks @mlehtima !
(I'm not sure why I didn't get a notification when I got pinged in this thread. It's weird...)

**Pull request closed without merging**
