### PR TITLE
[coverity] Suppress false positive. SX#GULBI-122

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by monich** [comment]
Just out of curiosity, what coverity complained about?

**Comment by martyone** [comment]
image

**Comment by monich** [comment]
I really don't get it - `disconnected` it checked as a loop condition and decremented at the bottom of the loop, how can it possibly overflow. And what is this _disconnected = disconnected, its value is now whatever._ That doesn't make any sense, does it?

**Comment by monich** [comment]
On the other hand, this `disconnected` count isn't really necessary (afaict it's just a micro-optimization for early termination of the loop) and can be removed without much of an impact. It would also make sense to remove the `GBinderServiceManagerWatch` entry when its last handler is gone. Let me try to rewrite this function in a way that makes coverity happier.

**Comment by martyone** [comment]
> I really don't get it - `disconnected` is checked as a loop condition and decremented at the bottom of the loop, how can it possibly overflow. And what is this _disconnected = disconnected, its value is now whatever._ That doesn't make any sense, does it?

Yes, it's clearly a false positive. Bug in the tool.

**Comment by monich** [comment]
BTW, what is this `SX#GULBI` thing? Looks like some sort of a magic necessary for the build to get through the build automation. Is it required? Does the old `JB#` magic still work?

**Comment by mkosola** [comment]
> BTW, what is this `SX#GULBI` thing? Looks like some sort of a magic necessary for the build to get through the build automation. Is it required? Does the old `JB#` magic still work?

@monich JB# is still used, SX# is just another similar bug reference code for different projects

**Comment by monich** [comment]
#141 is what I suggest instead

**Comment by monich** [comment]
I've merged #141 - this one can be closed I guess

**Pull request closed without merging**
