### PR TITLE
Utilize make_build macro. JB#61933

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Review by Thaodan — APPROVED** [review]
LGTM

**Comment by monich** [comment]
This makes the .spec files incompatible with rpm versions that don't have the `make_build` macro. What's the problem with `make %{_smp_mflags}` that this `make_build` thing is supposed to solve?

**Comment by Thaodan** [comment]
All rpm of the past 10 years should have %make_build, it was added about
11 years ago:
https://github.com/rpm-software-management/rpm/commit/89df36524bace71decee4ab4f979d4ffb449c9a7

The macro should be used to follow packaging conventions and to benefit
from improvements in the macro when rpm is updated.

**Comment by monich** [comment]
Well, it's "should", not "must". What kind of improvements are we talking about. Is it really worth the trouble.

My thinking goes like this. libgbinder isn't Sailfish OS specific, it's a generic library (binder is part of the upstream linux kernel) and as such, should be maintained in a state compatible "out of the box" with as many distros and build environments as possible.

So far I see a clear regression in the backward compatibility area and no obvious benefits.

**Comment by monich** [comment]
Oh well, never mind. I'll add a check if `make_build` is defined.

**Comment by pvuorela** [comment]
The upstream linux kernel part seems to be 3.19, 2015, when it was moved out of staging. That's some time after make_build.

**Comment by Thaodan** [comment]
> Well, it's "should", not "must". What kind of improvements are we talking about. Is it really worth the trouble.
> 
> My thinking goes like this. libgbinder isn't Sailfish OS specific, it's a generic library (binder is part of the upstream linux kernel) and as such, should be maintained in a state compatible "out of the box" with as many distros and build environments as possible.

Do you really want to support distributions that are 10 years old and don't even feature binder?

**Comment by monich** [comment]
The workaround for backward compatibility was simple, no problem, cheers.

**Pull request merged**
